# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Plantiga Playbook

on:
  workflow_dispatch:
    inputs:
      path:
        description: 'Path to the file to execute'
        required: true
      parameters:
        description: 'parameters to pass to the file'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Run Code
      run: |
        # stop the build if there are Python syntax errors or undefined names
        python .github/execute-plantiga-playbook.py "${{ github.event.inputs.path }}" "${{ github.event.inputs.parameters }}"

    - uses: actions/upload-artifact@v2
      with:
        name: log
        path: log.txt

    - uses: actions/upload-artifact@v2
      with:
        name: notebook
        path: notebook.ipynb
