# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

# inputs:
#   numOctocats:
#     description: 'Number of Octocats'
#     required: false
#     default: '1'
#   octocatEyeColor:
#     description: 'Eye color of the Octocats'
#     required: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Run Code
      run: |
        # stop the build if there are Python syntax errors or undefined names
        python foo.py
